"""Update user model for hex strings

Revision ID: 3dbfd5643c43
Revises: 
Create Date: 2020-04-24 01:31:55.436412

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3dbfd5643c43'
down_revision = None
branch_labels = ('default',)
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource', sa.Column('content', sa.Text(), nullable=False))
    op.add_column('resource', sa.Column('isfile', sa.Boolean(), nullable=False))
    op.add_column('resource', sa.Column('title', sa.Text(), nullable=False))
    op.add_column('resource', sa.Column('uid', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=True))
    op.create_unique_constraint(None, 'resource', ['uid'])
    op.drop_column('resource', 'name')
    op.drop_column('resource', 'contents')
    op.drop_column('resource', 'uuid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource', sa.Column('uuid', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False))
    op.add_column('resource', sa.Column('contents', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('resource', sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'resource', type_='unique')
    op.drop_column('resource', 'uid')
    op.drop_column('resource', 'title')
    op.drop_column('resource', 'isfile')
    op.drop_column('resource', 'content')
    # ### end Alembic commands ###
