"""actually update the user model

Revision ID: c8f888c14889
Revises: 3dbfd5643c43
Create Date: 2020-04-24 01:43:08.488145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c8f888c14889"
down_revision = "3dbfd5643c43"
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user",
        "salt",
        existing_type=sa.String(length=32),
        type_=sa.VARCHAR(length=64),
        existing_nullable=False,
    )
    op.alter_column(
        "user",
        "hash",
        existing_type=sa.String(length=256),
        type_=sa.VARCHAR(length=512),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user",
        "salt",
        existing_type=sa.String(length=64),
        type_=sa.VARCHAR(length=32),
        existing_nullable=False,
    )
    op.alter_column(
        "user",
        "hash",
        existing_type=sa.String(length=512),
        type_=sa.VARCHAR(length=256),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
